name: Java CI with Gradle

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build Jar
      run: ./gradlew shadowJar
    - name: Set jarFile
      run: echo "JARFILE=$(ls ./build/libs/*.jar| head -1)" >> $GITHUB_ENV
    - name: Get previously tag
      run: echo "PREV_TAG=$(git tag --sort=-creatordate | grep -A 1 env.RELEASE_VERSION | tail -n 1)" >> $GITHUB_ENV
    - name: Generate Changelog
      run: echo "CHANGES=$(echo $(git log $PREV_TAG..HEAD --oneline))" >> $GITHUB_ENV
    - name: push
      run: |
          git config --global user.name "Tronicbot"
          git config --global user.email "push@tronicbot.com"
          git add -A && git commit -m "[Auto] build.gradle -> ${env.RELEASE_VERSION}" && git push origin HEAD:master
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Version ${{ env.RELEASE_VERSION }}
        body: ${{ env.CHANGES }}
        draft: false
        prerelease: true
    - name: Generate Name
      run: echo "NAME=$(echo tronic-env.RELEASE_VERSION.jar)" >> $GITHUB_ENV
    - name: Upload Release Asset Jar
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ${{env.JARFILE}}
        asset_name: ${{env.NAME}}
        asset_content_type: application/java-archive
